### PR TITLE
For efinix

### PR DESCRIPTION
**Pull request by fjullien**
Not very happy with the changes. It complicates the code. At least it works.

### CODE REVIEW

**Comment by fjullien** [comment]
May be I could use a FSM like in hyperram_ddr2.py

**Comment by enjoy-digital** [comment]
Thanks @fjullien, it's generally not easy to get the simplest solution at first. Your PR looks good for me for this new 16-bit support.

To simplify it a bit without using an FSM, you could probably split  dt_seq` in three parts:
- Command + Latency wait.
- Write/Read Access.
- End of Access.

This way you'll be able to minimize the specialization to the Write/Read access that only seems to be the specific parts.

This should already be simple enough to be merged. I'm sure we'll also see other possible simplification after this (especially on the ca/bus.adr part) but we could do them progressively.

**Comment by fjullien** [comment]
I updated the PR with your suggestions

**Comment by enjoy-digital** [comment]
Thanks @fjullien, this is merged.

**Pull request merged**
